# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('reg_time', models.DateTimeField()),
                ('login_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-login_time'],
            },
        ),
    ]
