# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='username2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='passwd',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
