# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0002_auto_20161003_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlist',
            old_name='username',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='userlist',
            old_name='username2',
            new_name='lastname',
        ),
    ]
