# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0003_auto_20161003_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=1)),
                ('Title', models.CharField(max_length=1024)),
                ('Content', models.CharField(max_length=2048)),
                ('Createtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-Createtime'],
            },
        ),
    ]
